// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAueI5JjsTRlPIwAhisH6JzMNPMlXBrqeo',
    appId: '1:1088653590655:web:701c5e300816f4607cbf4a',
    messagingSenderId: '1088653590655',
    projectId: 'tstchatgp',
    authDomain: 'tstchatgp.firebaseapp.com',
    storageBucket: 'tstchatgp.appspot.com',
    measurementId: 'G-S290EG2KFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Fp1uptFoMJttABHbQM7Q34RvU3gEHN4',
    appId: '1:1088653590655:android:96b80f32da85a82a7cbf4a',
    messagingSenderId: '1088653590655',
    projectId: 'tstchatgp',
    storageBucket: 'tstchatgp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7WJCXsu1td1oYwAUBpNNnNf_Gr41c3pg',
    appId: '1:1088653590655:ios:b50113baf25506977cbf4a',
    messagingSenderId: '1088653590655',
    projectId: 'tstchatgp',
    storageBucket: 'tstchatgp.appspot.com',
    androidClientId: '1088653590655-r2olvrpgubv1lejeo5ss34d5b708kmo1.apps.googleusercontent.com',
    iosClientId: '1088653590655-8vbjll47ig65vp3qjc02lselbhr7orfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.qizologin2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7WJCXsu1td1oYwAUBpNNnNf_Gr41c3pg',
    appId: '1:1088653590655:ios:178fd9770042d3107cbf4a',
    messagingSenderId: '1088653590655',
    projectId: 'tstchatgp',
    storageBucket: 'tstchatgp.appspot.com',
    androidClientId: '1088653590655-r2olvrpgubv1lejeo5ss34d5b708kmo1.apps.googleusercontent.com',
    iosClientId: '1088653590655-cqucok8s6r29gjk1podhmg8g7v04hftj.apps.googleusercontent.com',
    iosBundleId: 'com.example.qizologin2.RunnerTests',
  );
}
